const GET_REQUEST = "GET_REQUEST";
const GET_SUCCESS = "GET_SUCCESS";
const GET_FAIL = "GET_FAIL";
const USER_SIGNIN = "USER_SIGNIN";
const ADD_TO_CART = "ADD_TO_CART";
const USER_SIGNOUT = "USERSIGNOUT";
export {
  GET_REQUEST,
  GET_SUCCESS,
  GET_FAIL,
  USER_SIGNIN,
  ADD_TO_CART,
  USER_SIGNOUT,
};
